apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
spec:
  rules:
  - host: ekstodoapp.tk
    http:
      paths:
      - path: /api/
        backend:
          serviceName: backend-to-do
          servicePort: 8080
